[package]
name = "panscape"
version = "0.1.0"
edition = "2021"

[dependencies]
charts = "0.3.0"
clap = { version = "4.5.29", features = ["derive"] }
cmd_lib = "1.9.5"
colored = "3.0.0"
rayon = "1.10.0"
regex = "1.11.1"
rusqlite = "0.33.0"
tabled = "0.18.0"
textwrap = "0.16.1"
